version: 2

sources:
  - name: honda_raw
    description: "Raw data from the mechanic's workshop (anonymized)."
    tables:
      - name: citas_honda
        description: "Operational logs of service appointments."